export default function riddles() {
  return {
  'riddles':[{
    'dID' : '1',
    'qText' : 'How many pieces are on a chessboard at the beginning of a game?',
    'qOptions' : ['32','28', '34','30'],
    'aText' : '32: Each opponent has 1 king, 1 queen, 2 rooks, 2 bishops, 2 knights, and 8 pawns.',
    'duration' : '120',
    'difficulty' : 'hard',
    'maxPoints' : '50',
  },
    {
      'dID' : '2',
      'qText' : 'You have a full box of matches and you go into a cold room. There is a coal furnace, a kerosene lamp and a fireplace. What do you light first?',
      'aText' : 'The match.',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID' : '3',
      'qText' : 'What word is displayed by these pictures?',
      'aText' : 'Calories',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID' : '4',
      'qText' : 'What word is displayed by these pictures?',
      'aText' : 'Racoon',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID' : '5',
      'qText' : 'Move one match to flip the chair over.',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '6',
      'qText' : 'What is the most popular coffee type in Austria?',
      'qOptions' : ['Cappuccino','Cafe Latte', 'Melange','Chai Latte'],
      'aText' : 'Cappuccino',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '7',
      'qText' : 'How long did the 30-year war last?',
      'aText' : '30 years',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '8',
      'qText' : 'What answer in all languages? What talks without mouth? What hears without ears?',
      'aText' : 'The Echo',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '9',
      'qText' : 'Which ist he longest river in the world?',
      'aText' : 'The Amazonas',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '10',
      'qText' : 'Name the capital city of France!',
      'aText' : 'Paris',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '11',
      'qText' : 'Which agent has the licence to kill?',
      'aText' : 'James Bond',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '12',
      'qText' : 'Which file format do you usually open with Acrobat Reader?',
      'aText' : 'PDF',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },

    {
      'dID': '13',
      'qText' : 'How many kidneys does a human being normally have?',
      'aText' : '2',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '14',
      'qText' : 'When did the Second World War end?',
      'qOptions' : ['1960','1945', '1939','1950'],
      'aText' : '1945',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '15',
      'qText' : 'What is the name of the second planet in our solar system?',
      'qOptions' : ['Venus','Jupiter', 'Mars','Earth'],
      'aText' : 'Venus',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '16',
      'qText' : 'What is a diamond made of?',
      'qOptions' : ['Carbon','Water', 'Gold','Sulphur'],
      'aText' : 'Carbon',
      'duration' : '60',
      'difficulty' : 'easy',
      'maxPoints' : '30',
    },
    {
      'dID': '17',
      'qText' : 'Which intolerance did Ötzi have?',
      'aText' : 'Lactose intolerance',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '18',
      'qText' : 'How many Christmas trees are sold in Germany each year?',
      'aText' : 'About 30 Millions.',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '19',
      'qText' : 'How many liter of beer are drunken by one person in Germany each year?',
      'aText' : '100 liter of beer',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '20',
      'qText' : 'How many letters are there in the Hawaiian alphabet?',
      'aText' : '12',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '21',
      'qText' : 'How many indentations does a golf ball have?',
      'aText' : '336',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '22',
      'qText' : 'Which planet is closest to the sun in our solar system?',
      'aText' : 'Mercury',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '23',
      'qText' : 'Which country is the second largest in the world in terms of its area?',
      'aText' : 'Canada',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '24',
      'qText' : 'In which city did the Olympic Games took place in 2000?',
      'aText' : 'Sydney',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '25',
      'qText' : 'Which city hast he biggest population in the world?',
      'aText' : 'Tokyo',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '26',
      'qText' : 'How many kilometres do you run during a marathon?',
      'qOptions' : ['60,105 km', '100 km','42,195 km','10 km'],
      'aText' : '42,195 km',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '27',
      'qText' : 'In which year was the Euro introduced?',
      'qOptions' : ['2003','2001', '2000','2002'],
      'aText' : '2002',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '28',
      'qText' : 'Who is the author of Star Wars?',
      'qOptions' : ['Roger Moore','Angela Merkel','George Lucas','Pierce Brosnan'],
      'aText' : 'George Lucas',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID': '29',
      'qText' : 'What is bronze made of?',
      'qOptions' : ['Acid and base','Copper and tin','Carbon and hydrogen','Sulphur and helium'],
      'aText' : 'Copper and tin',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID' : '30',
      'qText' : 'Move two matches so that the dog lives again!',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    },
    {
      'dID' : '31',
      'qText' : 'Move one match to correct the equation!',
      'duration' : '120',
      'difficulty' : 'hard',
      'maxPoints' : '50',
    }
    ]
  };
}
